Numpy is a Linear ALgebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in PyData Ecosystem rely on Numpy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

If you have Anaconda, install Numpy by going to our terminal or command prompt and typing
conda install numpy
pip install numpy


Numpy arrays essentially come in two flavors: vectors and matrices

Vectors are strictly 1-D arrays and matrices are 2-D (but matrice can also have one row or one column)

# Numpy Arrays

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as  np

In [4]:
arr=np.array(my_list)    #we can cast the above list as an array. SO we get the array back as the container for that list object

In [5]:
arr              #the above returns back one dimensional array

array([1, 2, 3])

If we want to get a 2 dimensional array or matrix, we can cast a list of lists

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)     #we get back 2 dimensional array  (cast normal python list of lists to a numpy array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Usually, however we will be using numpy's own built in generation methods to actually create arrays alot faster and a lot simpler.

In [10]:
np.arange(0,10)       #most common way to create arrays in numpy. Works like python own built in range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11)     #arange is the most common and simpler way to create an array in numpy quickly

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)     #3rd argument is step size 

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)          #to get arrays of zeros. (pass single number for 1D arrays)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))         #or pass in tuple of the dimensions we want

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,10)  #returns evenly spaced numbers over a specified interval. In this case, 10 evenly spaced numbers between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.linspace(0,5,5)     #returns 1-D vector(array) noted by one bracket

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [20]:
np.eye(4)                  #to get identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)      #rand is gonna create an array of the given shape we pass in and it's gonna populate it with random samples from uniform distribution between 0 and 1

array([0.31779406, 0.42027605, 0.99192743, 0.79946152, 0.54520569])

In [24]:
np.random.rand(5,5)     #don't need to pass the tuples as the argument, just pass the dimensions in this case

array([[0.64604162, 0.89523791, 0.23515741, 0.56591478, 0.98203063],
       [0.25221595, 0.28496137, 0.90847859, 0.48476917, 0.88242527],
       [0.71842093, 0.01916306, 0.89001023, 0.27482512, 0.04200768],
       [0.74637936, 0.95586933, 0.68069224, 0.56510854, 0.4721643 ],
       [0.76505601, 0.0780217 , 0.17891372, 0.1849947 , 0.97601016]])

In [27]:
np.random.randn(4)     #if we want to return samples from the standard normal(gaussian) distribution we use randn.Returns numbers from distribution centred around 0

array([ 1.30796181,  0.22078792,  0.92536437, -0.50584542])

In [9]:
np.random.randn(4,4)

array([[-0.48908293,  1.24641886,  0.62921196,  0.47492188],
       [-0.76452622,  0.37016666, -0.56358017, -0.76518742],
       [-0.66299251, -0.04558696, -1.73532916, -0.44800354],
       [-0.32399686,  0.30456674,  2.23871597,  1.50034834]])

In [10]:
np.random.randint(1,100,10)   #10 random integers between 1 and 100. Inclusive of low end and exclusve of higher end

array([29, 93, 84, 22, 82, 29, 31, 78, 62, 70])

In [11]:
arr=np.arange(25)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
randarr=np.random.randint(0,50,10)

In [14]:
randarr

array([ 5,  9, 20, 45, 22, 25, 29,  8, 49, 25])

In [15]:
arr.reshape(5,5)     #we can reshape arr into 5 by 5 matrix using reshape method

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
randarr

array([ 5,  9, 20, 45, 22, 25, 29,  8, 49, 25])

In [17]:
randarr.max()

49

In [18]:
randarr.min()

5

In [19]:
randarr.argmax()    #returns index position of the max value

8

In [20]:
randarr.argmin()

0

In [21]:
arr.shape     #output tells us that arr is 1 D

(25,)

In [22]:
arr=arr.reshape(5,5)

In [23]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.shape   #tells it is 2 D

(5, 5)

In [25]:
arr.dtype    #returns data type in an array

dtype('int32')

# Numpy Array Indexing

In [30]:
import numpy as np

In [31]:
arr=np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[8]      #value at index 8

8

In [34]:
arr[1:5]      #array slicing(not including index position 5)

array([1, 2, 3, 4])

In [35]:
arr[:5]   

array([0, 1, 2, 3, 4])

In [36]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

Numpy array differ from Normal Python list because of their ability to broadcast

In [37]:
arr[0:5]=100    #it is going to broadcast(change) those first 5 values to 100

In [38]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
arr=np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
slice_of_arr=arr[0:6]

In [42]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [43]:
slice_of_arr[:]=99

In [44]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [45]:
arr   #now when we call the arr, it has changed the original arr to 99's. So it is not creating a copy of an array but the reference of it.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

So, we can copy array as follows:

In [46]:
arr_copy=arr.copy()    #we specifically specify if we want a copy of the array using copy() method.

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_copy[:]=99

In [50]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [51]:
arr    #now original array is not changed only it's copy is changed

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Now we will learn about indexing the 2D array otherwise knwon as Matrix

In [32]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[0][0]    #gets element in the first row and first column

5

In [37]:
arr_2d[0]    #returns entire row 1

array([ 5, 10, 15])

In [38]:
arr_2d[1][1]

25

In [39]:
arr_2d[2][0]

35

In [41]:
arr_2d[2,0]    #single braket notation to get elements from 2D array.(Recomemnded method)

35

In [42]:
arr_2d[1,2]

30

Now let's say we didn't want single elements but the chunks of this 2D array.

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [47]:
arr_2d[:2]     #not includes row 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [48]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

Now, we will take a look at the conditional selection

In [67]:
arr=np.arange(1,11)

In [68]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
bool_arr=arr>5    #gives true whenever this comarison is true and false when the comparison is false (gives boolean array)

In [70]:
bool_arr   #the above gives true when values are greater than 5 not the indexes

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]      #we only get the results where the above boolean array happens to be true

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr>5]     #the above can also be done in a single statement. Just pass the conditional statement in the array

array([ 6,  7,  8,  9, 10])

In [74]:
arr[arr<3]    #this is the notation which will be used a lot.

array([1, 2])

In [75]:
arr_2d=np.arange(50).reshape(5,10)

In [76]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [81]:
arr_2d[1:3]    #not including 3   (when araay slicing better to get the rows first in this way, gets easy)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [82]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operations

1. Array with Array
2. Array with Scalars
3. Universal Array Functions

In [83]:
import numpy as np

In [84]:
arr=np.arange(0,11)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr+arr    #adds array element by element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [87]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [90]:
arr+10    #add 10 to every element in the array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [91]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [92]:
arr-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [93]:
arr/arr     #in this we will encounter 0/0 condition but numpy won't give an error instead it will just give warning. The remaining results results will be correct

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [95]:
1/arr    #get inf->infinity for 1/0 case

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [96]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [97]:
pow(arr,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Universal Array Functions: Numpy comes with many universal array functions which are essentially just mathematical equations we can use to perform the operations and broadcast it on the entire array.

In [99]:
np.sqrt(arr)       #square root of every elment in the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [100]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [101]:
np.max(arr)

10

In [102]:
arr.max()

10

In [103]:
np.sin(arr)   #pass in every element to sine

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [104]:
np.log(arr)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Numpy Exercise

In [105]:
import numpy as np

In [112]:
a=np.zeros(10)

In [113]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [114]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
a+5
#np.one(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [116]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [117]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [119]:
arr=np.arange(0,9)

In [120]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
np.random.rand(1)

array([0.03297182])

In [127]:
np.random.randn(25)

array([ 0.55276096, -0.49737955, -1.21100064, -1.13993134,  0.00282721,
        0.63183123, -0.05333755,  0.27303072, -0.08053365,  0.15405419,
        0.25060426,  0.51392067, -1.57935541, -1.84323321, -0.91867768,
        0.34656212, -1.4668464 ,  1.70874697, -0.21442664,  0.39235797,
       -0.5778413 , -1.02597511, -1.6519789 ,  0.33823521, -0.48176949])

In [133]:
arr1=np.linspace(0.01,1,100)

In [134]:
arr1

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [135]:
arr1.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [136]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [137]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [138]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [139]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [140]:
mat[3,4]

20

In [141]:
mat[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [144]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [145]:
mat[4]

array([21, 22, 23, 24, 25])

In [146]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [147]:
mat.sum()    #sum of all values in mat   #np.sum(mat)

325

In [149]:
mat.std()    #Get the standard deviation of the values in mat    #np.std(mat)

7.211102550927978

In [151]:
mat.sum(axis=0)    #get the sum of all the columns in mat    #mat.sum(axis=1)-->to get the sum of all the rows

array([55, 60, 65, 70, 75])